[package]
name = "zmu"
version = "0.1.0"
authors = ["Jarmo Torvinen <jarmo.torvinen@iki.fi>"]
edition = "2018"

[dependencies]
zmu_cortex_m = {path =  "zmu_cortex_m"}
bit_field = "0.7.0"
clap = "2.19"
tabwriter = "1"
error-chain = "0.12.0"
goblin = "0.0.12"
pad = "0.1.4"


[features]
default = ["armv7m"]


armv6m = ["zmu_cortex_m/armv6m"]
armv7m = ["zmu_cortex_m/armv7m"]
armv7em = ["zmu_cortex_m/armv7em"]