[package]
name = "zmu"
version = "0.1.0"
authors = ["Jarmo Torvinen <jarmo.torvinen@iki.fi>"]

[dependencies]
zmu_cortex_m = {path =  "zmu_cortex_m"}
bit_field = "0.7.0"
clap = "2.19"
tabwriter = "1"
error-chain = "0.12.0"
goblin = "0.0.12"
pad = "0.1.4"