[package]
name = "zmu_cortex_m"
version = "0.1.0"
authors = ["Jarmo Torvinen <jarmo.torvinen@iki.fi>"]
edition = "2018"

[dependencies]
byteorder = "0.3"
enum-set = "0.0.7"


[features]
armv6m = []
armv7m = []
armv7em = []